
#This configuration file contains the basic details of all organizations, channels and chaincodes
#important note: don't give similar names for organizations, channels and chaincodes.. if it is the configurations will not work properly..

Channels:
  blockchannel1:
    name: channel1
  blockchannel2:
    name: channel2
  blockchannel3:
    name: channel3
  blockchannel4:
    name: channel4
Org1:
  name: aic
  chaincode: fabcar_go1
Org2:
  name: bel
  chaincode: fabcar_go2
Org3:
  name: iiit
  chaincode: fabcar_go2
InterOrg:
  chaincode: fabcar_all

