OrdererOrgs:  
  - Name: Orderer
    Domain: ai.com
    EnableNodeOUs: true   
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5
