OrdererOrgs:  
  - Name: Orderer
    Domain: ai.com
    EnableNodeOUs: true   
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5
# PeerOrgs:
#   - Name: Org1
#     Domain: org1.ai.com
#     EnableNodeOUs: true    
#     Template:
#       Count: 1
#     Users:
#       Count: 1
#   - Name: Org2
#     Domain: org2.ai.com
#     EnableNodeOUs: true    
#     Template:
#       Count: 1
#     Users:
#       Count: 1
#   - Name: Org3
#     Domain: org3.ai.com
#     EnableNodeOUs: true    
#     Template:
#       Count: 1
#     Users:
#       Count: 1
#Organizations
#This is the end of the file          
